feat(logql/streamSelector): add init support for Object
MyUnisoft/sigyn pull request #159
Opened 2023-11-20 21:33 UTC by PierreDemailly

2023-11-21 06:49 UTC, Dafyh approved these changes

2023-11-21 09:30 UTC, fraxken requested changes

2023-11-21 09:30 UTC, fraxken commented on src/logql/src/streamSelector.ts
> +        continue;
remove all continue and use a proper elseif everywhere

2023-11-22 21:02 UTC, fraxken approved these changes

2023-11-23 15:57 UTC, merged